before_commands:
    - pip3 install cleo

build:
    dependencies:
        before:
          - pip3 install cleo
          - pip3 install coverage

    tests:
        before:
          - mysql

        override:
            -

                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'

