/**
 * Test for all possible types of parameters including LOB's.
 *
 * @param p_tst_bigint         Test parameter for bigint.
 * @param p_tst_int            Test parameter for int.
 * @param p_tst_smallint       Test parameter for smallint.
 * @param p_tst_tinyint        Test parameter for tinyint.
 * @param p_tst_bit            Test parameter for bit.
 * @param p_tst_money          Test parameter for money.
 * @param p_tst_smallmoney     Test parameter for smallmoney.
 * @param p_tst_decimal        Test parameter for decimal.
 * @param p_tst_numeric        Test parameter for numeric.
 * @param p_tst_float          Test parameter for float.
 * @param p_tst_real           Test parameter for real.
 * @param p_tst_date           Test parameter for date.
 * @param p_tst_datetime       Test parameter for datetime.
 * @param p_tst_datetime2      Test parameter for datetime2.
 * @param p_tst_datetimeoffset Test parameter for datetimeoffset.
 * @param p_tst_smalldatetime  Test parameter for smalldatetime.
 * @param p_tst_time           Test parameter for time.
 * @param p_tst_char           Test parameter for char.
 * @param p_tst_varchar        Test parameter for varchar.
 * @param p_tst_text           Test parameter for text.
 * @param p_tst_nchar          Test parameter for nchar.
 * @param p_tst_nvarchar       Test parameter for nvarchar.
 * @param p_tst_ntext          Test parameter for ntext.
 * @param p_tst_binary         Test parameter for binary.
 * @param p_tst_varbinary      Test parameter for varbinary.
 * @param p_tst_image          Test parameter for image.
 * @param p_tst_xml            Test parameter for xml.
 * @param p_tst_geography      Test parameter for geography.
 * @param p_tst_geometry       Test parameter for geometry.
 */
create procedure dbo.tst_parameter_types02
  @p_tst_bigint         @dbo.tst_foo1.tst_bigint%type@,
  @p_tst_int            @dbo.tst_foo1.tst_int%type@,
  @p_tst_smallint       @dbo.tst_foo1.tst_smallint%type@,
  @p_tst_tinyint        @dbo.tst_foo1.tst_tinyint%type@,
  @p_tst_bit            @dbo.tst_foo1.tst_bit%type@,
  @p_tst_money          @dbo.tst_foo1.tst_money%type@,
  @p_tst_smallmoney     @dbo.tst_foo1.tst_smallmoney%type@,
  @p_tst_decimal        @dbo.tst_foo1.tst_decimal%type@,
  @p_tst_numeric        @dbo.tst_foo1.tst_numeric%type@,
  @p_tst_float          @dbo.tst_foo1.tst_float%type@,
  @p_tst_real           @dbo.tst_foo1.tst_real%type@,
  @p_tst_date           @dbo.tst_foo1.tst_date%type@,
  @p_tst_datetime       @dbo.tst_foo1.tst_datetime%type@,
  @p_tst_datetime2      @dbo.tst_foo1.tst_datetime2%type@,
  @p_tst_datetimeoffset @dbo.tst_foo1.tst_datetimeoffset%type@,
  @p_tst_smalldatetime  @dbo.tst_foo1.tst_smalldatetime%type@,
  @p_tst_time           @dbo.tst_foo1.tst_time%type@,
  @p_tst_char           @dbo.tst_foo1.tst_char%type@,
  @p_tst_varchar        @dbo.tst_foo1.tst_varchar%type@,
  @p_tst_text           @dbo.tst_foo1.tst_text%type@,
  @p_tst_nchar          @dbo.tst_foo1.tst_nchar%type@,
  @p_tst_nvarchar       @dbo.tst_foo1.tst_nvarchar%type@,
  @p_tst_ntext          @dbo.tst_foo1.tst_ntext%type@,
  @p_tst_binary         @dbo.tst_foo1.tst_binary%type@,
  @p_tst_varbinary      @dbo.tst_foo1.tst_varbinary%type@,
  @p_tst_image          @dbo.tst_foo1.tst_image%type@,
  @p_tst_xml            @dbo.tst_foo1.tst_xml%type@,
  @p_tst_geography      @dbo.tst_foo1.tst_geography%type@,
  @p_tst_geometry       @dbo.tst_foo1.tst_geometry%type@
-- type: none
as
insert into TST_FOO1( tst_bigint,
                      tst_int,
                      tst_smallint,
                      tst_tinyint,
                      tst_bit,
                      tst_money,
                      tst_smallmoney,
                      tst_decimal,
                      tst_numeric,
                      tst_float,
                      tst_real,
                      tst_date,
                      tst_datetime,
                      tst_datetime2,
                      tst_datetimeoffset,
                      tst_smalldatetime,
                      tst_time,
                      tst_char,
                      tst_varchar,
                      tst_text,
                      tst_nchar,
                      tst_nvarchar,
                      tst_ntext,
                      tst_binary,
                      tst_varbinary,
                      tst_image,
                      tst_xml,
                      tst_geography,
                      tst_geometry )
values( @p_tst_bigint,
        @p_tst_int,
        @p_tst_smallint,
        @p_tst_tinyint,
        @p_tst_bit,
        @p_tst_money,
        @p_tst_smallmoney,
        @p_tst_decimal,
        @p_tst_numeric,
        @p_tst_float,
        @p_tst_real,
        @p_tst_date,
        @p_tst_datetime,
        @p_tst_datetime2,
        @p_tst_datetimeoffset,
        @p_tst_smalldatetime,
        @p_tst_time,
        @p_tst_char,
        @p_tst_varchar,
        @p_tst_text,
        @p_tst_nchar,
        @p_tst_nvarchar,
        @p_tst_ntext,
        @p_tst_binary,
        @p_tst_varbinary,
        @p_tst_image,
        @p_tst_xml,
        @p_tst_geography,
        @p_tst_geometry )
        ;

